name: "Release"

on: 
  release:
    types:
      - published

jobs:
  release:
    name: "Publish to crates.io"
    runs-on: "ubuntu-latest"
    steps:
      - name: "[SETUP] Checkout"
        uses: "actions/checkout@v3"
        with:
          fetch-depth: 0
      - name: "[SETUP] Rust Toolchain"
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: "[PUBLISH] Cargo"
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
        run: cargo publish
